# Generated by Django 5.2.2 on 2025-07-01 20:14

import django.db.models.deletion
import processes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_documento', models.CharField(max_length=50)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('FC', 'Ficha de caracterización'), ('MA', 'Matriz'), ('PR', 'Procedimiento'), ('DI', 'Documento interno'), ('GU', 'Guía'), ('PT', 'Protocolo'), ('PL', 'Plan'), ('IN', 'Instructivo'), ('FR', 'Formato'), ('DE', 'Documento externo')], max_length=3)),
                ('version', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('VIG', 'Vigente'), ('OBS', 'Obsoleto')], default='VIG', max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo_oficial', models.FileField(upload_to='documentos/oficiales/', validators=[processes.models.validar_archivo_oficial])),
                ('archivo_editable', models.FileField(blank=True, null=True, upload_to='documentos/editables/', validators=[processes.models.validar_archivo_editable])),
                ('documento_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones', to='processes.documento')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.process')),
            ],
            options={
                'indexes': [models.Index(fields=['codigo_documento'], name='processes_d_codigo__e2fd78_idx'), models.Index(fields=['tipo_documento'], name='processes_d_tipo_do_ed41a7_idx'), models.Index(fields=['estado'], name='processes_d_estado_58e216_idx')],
                'unique_together': {('codigo_documento', 'version')},
            },
        ),
    ]
