# Generated by Django 5.2.2 on 2025-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('VIG', 'Vigente'), ('OBS', 'Obsoleto')], default='VIG', max_length=3),
        ),
    ]
