# Generated by Django 5.2.2 on 2025-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTercero',
            fields=[
                ('tercero_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo del tercero')),
            ],
            options={
                'verbose_name': 'Tipo de tercero',
                'verbose_name_plural': 'Tipo de terceros',
                'db_table': 'terceros_tipotercero',
            },
        ),
    ]
