# Generated by Django 5.2.2 on 2025-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='departamento_codigo',
            field=models.CharField(default=1, max_length=100, verbose_name='codigo del departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='municipio_codigo',
            field=models.CharField(default=1, max_length=100, verbose_name='codigo del municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='pais_codigo',
            field=models.CharField(default=1, max_length=100, verbose_name='codigo del país'),
            preserve_default=False,
        ),
    ]
