# Generated by Django 5.2.2 on 2025-07-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0002_tipotercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='tercero_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terceros_departamento', to='tercero.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_direccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_estado',
            field=models.BooleanField(default=True, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terceros_municipio', to='tercero.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_obligado_facturar',
            field=models.BooleanField(default=False, null=True, verbose_name='Obligado a facturar'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terceros_pais', to='tercero.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_proveedor',
            field=models.BooleanField(default=False, null=True, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tercero.tipotercero', verbose_name='Tipo de tercero'),
        ),
    ]
