# Generated by Django 5.2.2 on 2025-07-03 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0002_tipotercero_alter_terceros_tercero_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='tercero_tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tercero.tipotercero', verbose_name='Tipo de tercero'),
        ),
    ]
