# Generated by Django 5.2.2 on 2025-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0004_alter_terceros_tercero_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='tercero_tipo',
            field=models.BooleanField(default=False, null=True, verbose_name='Tipo tercero'),
        ),
        migrations.DeleteModel(
            name='TipoTercero',
        ),
    ]
