# Generated by Django 5.2.2 on 2025-07-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0004_alter_terceros_tercero_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='tercero_apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tercero_nombres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
    ]
