# Generated by Django 5.2.2 on 2025-07-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0005_alter_terceros_tercero_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terceros',
            name='tercero_apellidos',
        ),
        migrations.RemoveField(
            model_name='terceros',
            name='tercero_nombres',
        ),
        migrations.AddField(
            model_name='terceros',
            name='tercero_nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo'),
        ),
    ]
