# Generated by Django 5.2.2 on 2025-06-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CausalDevolucion',
            fields=[
                ('causalid', models.AutoField(primary_key=True, serialize=False)),
                ('causal_nombre', models.CharField(default='', max_length=200)),
                ('causal_fecha', models.DateField(blank=True, null=True)),
                ('causal_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Causal Devolución',
                'verbose_name_plural': 'CAUSAL DEVOLUCIONES',
            },
        ),
        migrations.CreateModel(
            name='CentroCostos',
            fields=[
                ('costos_id', models.AutoField(primary_key=True, serialize=False)),
                ('costos_nombre_sede', models.CharField(default='', max_length=250)),
                ('costos_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'CENTRO DE COSTOS',
            },
        ),
        migrations.CreateModel(
            name='CentroOperaciones',
            fields=[
                ('operaciones_id', models.AutoField(primary_key=True, serialize=False)),
                ('operaciones_nombre', models.CharField(default='', max_length=250)),
                ('operaciones_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de operacion',
                'verbose_name_plural': 'CENTRO DE OPERACIONES',
            },
        ),
        migrations.CreateModel(
            name='DocumentoContable',
            fields=[
                ('doc_contable_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_contable_tipo', models.CharField(default='', max_length=250)),
                ('doc_contable_descripcion', models.TextField(blank=True, null=True)),
                ('doc_contable_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento contable',
                'verbose_name_plural': 'DOCUMENTOS CONTABLES',
            },
        ),
        migrations.CreateModel(
            name='EstadoRevision',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del estado')),
            ],
            options={
                'verbose_name': 'Estado de revisión',
                'verbose_name_plural': 'Estados de revisión',
                'db_table': 'gestionProveedores_estadorevision',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_id_factura_electronica', models.CharField(default='', max_length=100, verbose_name='ID FE')),
                ('factura_etapa', models.CharField(default='', max_length=50, verbose_name='Etapa')),
                ('factura_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('factura_estado_factura', models.IntegerField(default=0, verbose_name='Estado de la factura')),
                ('factura_numero_autorizacion', models.CharField(default='', max_length=100, verbose_name='Factura autorizada')),
                ('factura_concepto', models.TextField(default='', verbose_name='Concepto')),
                ('factura_razon_social_proveedor', models.CharField(default='', max_length=150, verbose_name='Razón social proveedor')),
                ('factura_razon_social_adquiriente', models.CharField(default='', max_length=150, verbose_name='Razón social adquiriente')),
                ('factura_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='valor')),
                ('factura_estado', models.BooleanField(default=True)),
                ('causal_anulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulaciones', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución por anulación')),
                ('causal_contabilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contabilidades', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución por contabilidad')),
                ('causal_impuestos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impuestos', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución por impuestos')),
                ('causal_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución por revisión')),
                ('factura_centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_costos', to='gestionProveedores.centrocostos', verbose_name='Centro de costo')),
                ('factura_centro_operaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_operaciones', to='gestionProveedores.centrooperaciones', verbose_name='Centro de operaciones')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'FACTURAS ELECTRÓNICAS PRINCIPAL',
            },
        ),
        migrations.CreateModel(
            name='FacturaElectronicaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionFactura', models.TextField(default='', verbose_name='Descripción')),
                ('observacionesGestion', models.TextField(blank=True, null=True, verbose_name='Observaciones de gestión')),
                ('observacionesInconsistencias', models.TextField(blank=True, null=True, verbose_name='Observaciones de inconsistencias')),
                ('observacionesConformidad', models.TextField(blank=True, null=True, verbose_name='Observaciones de conformidad')),
                ('observacionesPago', models.TextField(blank=True, null=True, verbose_name='Observaciones de pago')),
                ('observacionesContabilidad', models.TextField(blank=True, null=True, verbose_name='Observaciones de contabilidad')),
                ('observacionesRevision', models.TextField(blank=True, null=True, verbose_name='Observaciones de revisión')),
                ('observacionesImpuestos', models.TextField(blank=True, null=True, verbose_name='Observaciones de impuestos')),
                ('observacionesContraloria', models.TextField(blank=True, null=True, verbose_name='Observaciones de contraloría')),
                ('estado', models.CharField(default='', max_length=50)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Factura Detalle',
                'verbose_name_plural': 'DETALLES DE LAS FACTURAS',
            },
        ),
        migrations.CreateModel(
            name='GestionarFactura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_estado_factura', models.IntegerField(default=0, verbose_name='Estado de la factura')),
                ('factura_estado', models.BooleanField(default=True)),
                ('observaciones_gestion', models.TextField(blank=True, null=True, verbose_name='Observaciones gestión')),
                ('causal_devolucion_anulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulaciones_gestionar', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución por anulación')),
                ('factura_centro_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_operaciones_gestionar', to='gestionProveedores.centrooperaciones', verbose_name='Centro de operaciones')),
                ('factura_relacionada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_factura', to='gestionProveedores.factura', verbose_name='Factura relacionada')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Etapa 1 : Gestión F.E.',
            },
        ),
        migrations.CreateModel(
            name='PendientePago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('pago_realizo_pago', models.BooleanField(default=True)),
                ('pago_soportes', models.BooleanField(default=True)),
                ('pago_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_pagos', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Pendiente pago',
                'verbose_name_plural': 'PENDIENTES PAGOS',
            },
        ),
        migrations.CreateModel(
            name='PendienteReconocimientoContable',
            fields=[
                ('contable_id', models.AutoField(primary_key=True, serialize=False)),
                ('contable_NIT_prestador', models.CharField(default='', max_length=150)),
                ('contable_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_contables', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Pendiente reconocimiento contable',
                'verbose_name_plural': 'PENDIENTES RECONOCIMIENTOS CONTABLES',
            },
        ),
        migrations.CreateModel(
            name='PendienteRevision',
            fields=[
                ('revision_id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_estado', models.BooleanField(default=True)),
                ('revision_observacion_revision', models.TextField(blank=True, null=True, verbose_name='Observaciones revisión')),
                ('factura_relacionada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_factura', to='gestionProveedores.factura', verbose_name='Factura relacionada')),
                ('revision_causal_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_devolucion', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución por revisión')),
                ('revision_centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_costos', to='gestionProveedores.centrocostos', verbose_name='Centro de costo')),
                ('revision_estado_revision', models.ForeignKey(blank=True, db_column='revision_estado_revision_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionProveedores.estadorevision', verbose_name='Estado revisión')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Etapa 2 : Pendiente Revisión',
            },
        ),
        migrations.CreateModel(
            name='RevisionContraloria',
            fields=[
                ('contraloria_id', models.AutoField(primary_key=True, serialize=False)),
                ('contraloria_estado_contraloria', models.IntegerField(default=0)),
                ('contraloria_observaciones', models.TextField(blank=True, null=True)),
                ('contraloria_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_contraloria', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Revisión contraloría',
                'verbose_name_plural': 'REVISIÓN CONTRALORÍAS',
            },
        ),
        migrations.CreateModel(
            name='RevisionImpuestos',
            fields=[
                ('revision_impuestos_id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_impuestos_estado_impuestos', models.IntegerField(default=0)),
                ('revision_impuestos_observaciones', models.TextField(blank=True, null=True)),
                ('revision_impuestos_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_impuestos', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Revisión impuestos',
                'verbose_name_plural': 'REVISIÓN IMPUESTOS',
            },
        ),
    ]
