# Generated by Django 5.2.2 on 2025-06-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausalDevolucion',
            fields=[
                ('causalid', models.AutoField(primary_key=True, serialize=False)),
                ('causal_nombre', models.CharField(default='', max_length=200)),
                ('causal_fecha', models.DateField(blank=True, null=True)),
                ('causal_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Causal Devolución',
                'verbose_name_plural': 'CAUSAL DEVOLUCIONES',
            },
        ),
        migrations.CreateModel(
            name='CentroCostos',
            fields=[
                ('costos_id', models.AutoField(primary_key=True, serialize=False)),
                ('costos_nombre_sede', models.CharField(default='', max_length=250)),
                ('costos_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'CENTRO DE COSTOS',
            },
        ),
        migrations.CreateModel(
            name='CentroOperaciones',
            fields=[
                ('operaciones_id', models.AutoField(primary_key=True, serialize=False)),
                ('operaciones_nombre', models.CharField(default='', max_length=250)),
                ('operaciones_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de operacion',
                'verbose_name_plural': 'CENTRO DE OPERACIONES',
            },
        ),
        migrations.CreateModel(
            name='DocumentoContable',
            fields=[
                ('doc_contable_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_contable_tipo', models.CharField(default='', max_length=250)),
                ('doc_contable_descripcion', models.TextField(blank=True, null=True)),
                ('doc_contable_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento contable',
                'verbose_name_plural': 'DOCUMENTOS CONTABLES',
            },
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'FACTURAS ELECTRÓNICAS'},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_concepto',
            field=models.TextField(default='', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_estado_factura',
            field=models.IntegerField(default=0, verbose_name='Estado de la factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_etapa',
            field=models.CharField(default='', max_length=50, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_id_factura_electronica',
            field=models.CharField(default='', max_length=100, verbose_name='ID FE'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_numero_autorizacion',
            field=models.CharField(default='', max_length=100, verbose_name='Factura autorizada'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_razon_social_adquiriente',
            field=models.CharField(default='', max_length=150, verbose_name='Razón social adquiriente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_razon_social_proveedor',
            field=models.CharField(default='', max_length=150, verbose_name='Razón social proveedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='valor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='causal_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulaciones', to='gestionProveedores.causaldevolucion', verbose_name='Causal de anulación'),
        ),
        migrations.AddField(
            model_name='factura',
            name='causal_contabilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contabilidades', to='gestionProveedores.causaldevolucion', verbose_name='Causal de contabilidad'),
        ),
        migrations.AddField(
            model_name='factura',
            name='causal_impuestos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impuestos', to='gestionProveedores.causaldevolucion', verbose_name='Causal de impuestos'),
        ),
        migrations.AddField(
            model_name='factura',
            name='causal_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to='gestionProveedores.causaldevolucion', verbose_name='Causal de devolución'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_costos', to='gestionProveedores.centrocostos', verbose_name='Centro de costo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_centro_operaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_operaciones', to='gestionProveedores.centrooperaciones', verbose_name='Centro de operaciones'),
        ),
        migrations.CreateModel(
            name='FacturaElectronicaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionFactura', models.TextField(default='', verbose_name='Descripción')),
                ('observacionesGestion', models.TextField(blank=True, null=True, verbose_name='Observaciones de gestión')),
                ('observacionesInconsistencias', models.TextField(blank=True, null=True, verbose_name='Observaciones de inconsistencias')),
                ('observacionesConformidad', models.TextField(blank=True, null=True, verbose_name='Observaciones de conformidad')),
                ('observacionesPago', models.TextField(blank=True, null=True, verbose_name='Observaciones de pago')),
                ('observacionesContabilidad', models.TextField(blank=True, null=True, verbose_name='Observaciones de contabilidad')),
                ('observacionesRevision', models.TextField(blank=True, null=True, verbose_name='Observaciones de revisión')),
                ('observacionesImpuestos', models.TextField(blank=True, null=True, verbose_name='Observaciones de impuestos')),
                ('observacionesContraloria', models.TextField(blank=True, null=True, verbose_name='Observaciones de contraloría')),
                ('estado', models.CharField(default='', max_length=50)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Factura Detalle',
                'verbose_name_plural': 'DETALLES DE LAS FACTURAS',
            },
        ),
        migrations.CreateModel(
            name='PendientePago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('pago_realizo_pago', models.BooleanField(default=True)),
                ('pago_soportes', models.BooleanField(default=True)),
                ('pago_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_pagos', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Pendiente pago',
                'verbose_name_plural': 'PENDIENTES PAGOS',
            },
        ),
        migrations.CreateModel(
            name='PendienteReconocimientoContable',
            fields=[
                ('contable_id', models.AutoField(primary_key=True, serialize=False)),
                ('contable_NIT_prestador', models.CharField(default='', max_length=150)),
                ('contable_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_contables', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Pendiente reconocimiento contable',
                'verbose_name_plural': 'PENDIENTES RECONOCIMIENTOS CONTABLES',
            },
        ),
        migrations.CreateModel(
            name='PendienteRevision',
            fields=[
                ('revision_id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_fecha_gestion', models.DateField(blank=True, null=True)),
                ('revision_fecha_recibe', models.DateField(blank=True, null=True)),
                ('revision_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_revision', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Pendiente Revisión',
                'verbose_name_plural': 'PENDIENTES REVISIÓN',
            },
        ),
        migrations.CreateModel(
            name='RevisionContraloria',
            fields=[
                ('contraloria_id', models.AutoField(primary_key=True, serialize=False)),
                ('contraloria_estado_contraloria', models.IntegerField(default=0)),
                ('contraloria_observaciones', models.TextField(blank=True, null=True)),
                ('contraloria_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_contraloria', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Revisión contraloría',
                'verbose_name_plural': 'REVISIÓN CONTRALORÍAS',
            },
        ),
        migrations.CreateModel(
            name='RevisionImpuestos',
            fields=[
                ('revision_impuestos_id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_impuestos_estado_impuestos', models.IntegerField(default=0)),
                ('revision_impuestos_observaciones', models.TextField(blank=True, null=True)),
                ('revision_impuestos_estado', models.BooleanField(default=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_impuestos', to='gestionProveedores.factura')),
            ],
            options={
                'verbose_name': 'Revisión impuestos',
                'verbose_name_plural': 'REVISIÓN IMPUESTOS',
            },
        ),
    ]
