# Generated by Django 5.2.2 on 2025-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendienterevision',
            name='revision_fecha_gestion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendienterevision',
            name='revision_fecha_recibe',
            field=models.DateField(blank=True, null=True),
        ),
    ]
