# Generated by Django 5.2.2 on 2025-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='factura_concepto',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_etapa',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_id_factura_electronica',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ID FE'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_numero_autorizacion',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Factura autorizada'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_razon_social_adquiriente',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Razón social adquiriente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_razon_social_proveedor',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Razón social proveedor'),
        ),
    ]
