# Generated by Django 5.2.2 on 2025-06-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0002_pendienterevision_revision_fecha_gestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPendienteRContable',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del estado')),
            ],
            options={
                'verbose_name': 'Estado de pendiente reconocimiento contable',
                'verbose_name_plural': 'Estados de pendientes de reconocimientos contables',
                'db_table': 'gestionProveedores_estadopendientercontable',
            },
        ),
        migrations.AddField(
            model_name='pendientereconocimientocontable',
            name='contable_causal_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendientes_reconocimiento_contable', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución por pendiente reconocimiento contable'),
        ),
        migrations.AddField(
            model_name='pendientereconocimientocontable',
            name='contable_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionProveedores.documentocontable'),
        ),
        migrations.AddField(
            model_name='pendientereconocimientocontable',
            name='contable_numero_documento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pendientereconocimientocontable',
            name='contable_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendientereconocimientocontable',
            name='contable_estado_reconocimiento_contable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionProveedores.estadopendientercontable'),
        ),
    ]
