# Generated by Django 5.2.2 on 2025-06-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0003_estadopendientercontable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendientereconocimientocontable',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Etapa 3 : Pendiente Reconocimiento Contable'},
        ),
    ]
