# Generated by Django 5.2.2 on 2025-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0004_alter_pendientereconocimientocontable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocostos',
            name='costos_codigo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
