# Generated by Django 5.2.2 on 2025-06-26 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0005_centrocostos_costos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendienterevision',
            name='revision_estado_revision',
            field=models.ForeignKey(db_column='revision_estado_revision_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='gestionProveedores.estadorevision', verbose_name='Estado revisión'),
        ),
    ]
