# Generated by Django 5.2.2 on 2025-06-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0006_alter_pendienterevision_revision_estado_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del estado')),
            ],
            options={
                'verbose_name': 'Estado de factura',
                'verbose_name_plural': 'Estados de facturas',
                'db_table': 'gestionProveedores_estadofactura',
            },
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_estado_factura',
            field=models.ForeignKey(db_column='factura_estado_factura_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='gestionProveedores.estadofactura', verbose_name='Estado factura'),
        ),
    ]
