# Generated by Django 5.2.2 on 2025-06-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0007_estadofactura_alter_factura_factura_estado_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionarfactura',
            name='factura_estado_factura',
        ),
        migrations.AddField(
            model_name='gestionarfactura',
            name='factura_estado_factura_gestion',
            field=models.ForeignKey(db_column='factura_estado_factura_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='gestionProveedores.estadofactura', verbose_name='Estado factura'),
        ),
    ]
