# Generated by Django 5.2.2 on 2025-07-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0008_remove_gestionarfactura_factura_estado_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionimpuestos',
            name='revision_impuestos_causal_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_impuestos', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución por revisión impuestos'),
        ),
    ]
