# Generated by Django 5.2.2 on 2025-07-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0009_revisionimpuestos_revision_impuestos_causal_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoImpuestos',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del estado')),
            ],
            options={
                'verbose_name': 'Estado de impuesto',
                'verbose_name_plural': 'Estados de impuestos',
                'db_table': 'gestionProveedores_estadoimpuestos',
            },
        ),
        migrations.AlterModelOptions(
            name='revisionimpuestos',
            options={'verbose_name': 'Revisión impuestos', 'verbose_name_plural': 'Etapa 4 : Revisión Impuestos'},
        ),
    ]
