# Generated by Django 5.2.2 on 2025-07-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0010_estadoimpuestos_alter_revisionimpuestos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoContraloria',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del estado')),
            ],
            options={
                'verbose_name': 'Estado de contraloría',
                'verbose_name_plural': 'Estados de contraloría',
                'db_table': 'gestionProveedores_estadocontraloria',
            },
        ),
        migrations.AlterModelOptions(
            name='pendientepago',
            options={'verbose_name': 'Pendiente pago', 'verbose_name_plural': 'Etapa 6: Tesorería/Pendiente Pagos'},
        ),
        migrations.AlterModelOptions(
            name='revisioncontraloria',
            options={'verbose_name': 'Revisión contraloría', 'verbose_name_plural': 'Etapa 5: Revisión Contraloría'},
        ),
        migrations.AlterField(
            model_name='revisionimpuestos',
            name='revision_impuestos_estado_impuestos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionProveedores.estadoimpuestos'),
        ),
    ]
