# Generated by Django 5.2.2 on 2025-07-01 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0011_estadocontraloria_alter_pendientepago_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisioncontraloria',
            name='contraloria_estado_contraloria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionProveedores.estadocontraloria'),
        ),
    ]
