# Generated by Django 5.2.2 on 2025-07-01 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0012_alter_revisioncontraloria_contraloria_estado_contraloria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('date_received', models.DateTimeField()),
                ('raw_message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='causaldevolucion',
            name='causal_estado',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='causaldevolucion',
            name='causal_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='causaldevolucion',
            name='causal_nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='causaldevolucion',
            name='causalid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='centrocostos',
            name='costos_codigo',
            field=models.CharField(default='', max_length=100, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='centrocostos',
            name='costos_estado',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='centrocostos',
            name='costos_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='centrocostos',
            name='costos_nombre_sede',
            field=models.CharField(default='', max_length=250, verbose_name='Nombre sede'),
        ),
        migrations.AlterField(
            model_name='centrooperaciones',
            name='operaciones_estado',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='centrooperaciones',
            name='operaciones_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='centrooperaciones',
            name='operaciones_nombre',
            field=models.CharField(default='', max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documentocontable',
            name='doc_contable_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documentocontable',
            name='doc_contable_estado',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentocontable',
            name='doc_contable_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentocontable',
            name='doc_contable_tipo',
            field=models.CharField(default='', max_length=250, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='gestionarfactura',
            name='causal_devolucion_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulaciones_gestionar', to='gestionProveedores.causaldevolucion', verbose_name='Causal Devolución y/o Anulación'),
        ),
        migrations.AlterField(
            model_name='gestionarfactura',
            name='factura_estado',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gestionarfactura',
            name='factura_estado_factura_gestion',
            field=models.ForeignKey(db_column='factura_estado_factura_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='gestionProveedores.estadofactura', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pendientereconocimientocontable',
            name='contable_NIT_prestador',
            field=models.CharField(default='', max_length=150, verbose_name='NIT Prestador'),
        ),
        migrations.AlterField(
            model_name='pendientereconocimientocontable',
            name='contable_causal_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendientes_reconocimiento_contable', to='gestionProveedores.causaldevolucion', verbose_name='Causal Devolución'),
        ),
        migrations.AlterField(
            model_name='pendientereconocimientocontable',
            name='contable_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionProveedores.documentocontable', verbose_name='Documento_Contable'),
        ),
        migrations.AlterField(
            model_name='pendientereconocimientocontable',
            name='contable_estado',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pendientereconocimientocontable',
            name='contable_estado_reconocimiento_contable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionProveedores.estadopendientercontable', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pendientereconocimientocontable',
            name='contable_numero_documento',
            field=models.CharField(default='', max_length=100, verbose_name='Número Documento'),
        ),
        migrations.AlterField(
            model_name='pendientereconocimientocontable',
            name='contable_observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='pendienterevision',
            name='revision_causal_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_devolucion', to='gestionProveedores.causaldevolucion', verbose_name='Causal devolución'),
        ),
        migrations.AlterField(
            model_name='pendienterevision',
            name='revision_centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_costos', to='gestionProveedores.centrocostos', verbose_name='Centro Costo'),
        ),
        migrations.AlterField(
            model_name='pendienterevision',
            name='revision_estado',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pendienterevision',
            name='revision_estado_revision',
            field=models.ForeignKey(db_column='revision_estado_revision_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='gestionProveedores.estadorevision', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pendienterevision',
            name='revision_observacion_revision',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
