# Generated by Django 5.2.2 on 2025-07-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0013_correo_alter_causaldevolucion_causal_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='adjuntos/')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='gestionProveedores.correo')),
            ],
        ),
    ]
