# Generated by Django 5.2.2 on 2025-07-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0014_archivoadjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='archivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
