# Generated by Django 5.2.2 on 2025-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0015_correo_archivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='uid',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='correo',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
    ]
