# Generated by Django 5.2.2 on 2025-07-01 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='processType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.processtype'),
        ),
    ]
