# Generated by Django 5.2.2 on 2025-06-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_processtype_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
            preserve_default=False,
        ),
    ]
