# Generated by Django 5.2.2 on 2025-06-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_processtype_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='companies.department'),
            preserve_default=False,
        ),
    ]
